npm install -g babel-eslint
npm install -g coffee-script
npm install -g eslint
npm install -g express
npm install -g grunt-cli
npm install -g gulp
npm install -g hexo
#npm install -g html2jade
npm install -g jslint
npm install -g karma
npm install -g mean-cli
npm install -g mocha
npm install -g nodemon
npm install -g yo
npm install -g uglify-js
