npm install -g generator-angular-fullstack
npm install -g babel-eslint
npm install -g browser-sync
#npm install -g coffee-script
npm install -g eslint
npm install -g express
npm install -g grunt-cli
npm install -g gulp
npm install -g gulp-concat
npm install -g gulp-jshint
npm install -g gulp-rename
npm install -g gulp-sass
npm install -g gulp-uglify
npm install -g hexo
#npm install -g html2jade
npm install -g jslint
#npm install -g karma
# npm install -g mean-cli
npm install -g mocha
npm install -g nodemon
npm install -g react
npm install -g react-dom
npm install -g yo
npm install -g uglify-js
