apm install atom-beautify
apm install autocomplete-plus
apm install autocomplete-snippets
apm install color-picker
apm install editor-stats
apm install emmet
apm install file-icons
apm install filetype-color
apm install jshint
apm install linter
apm install merge-conflicts
apm install terminal-status
apm install todo-show
apm install vim-mode
