apm install atom-beautify
apm install atom-color-highlight
apm install atom-ctags
apm install atom-pair
apm install autocomplete-plus
apm install autocomplete-snippets
apm install color-picker
apm install easy-motion
apm install editor-stats
apm install emmet
apm install file-icons
apm install filetype-color
apm install git-plus
apm install git-tab-status
apm install highlight-line
apm install highlight-selected
apm install japanese-wrap
apm install jshint
apm install language-scheme
apm install linter
apm install linter-coffeelint
apm install linter-jshint
apm install minimap
apm install minimap-highlight-selected
apm install merge-conflicts
apm install mocha-test-runner
apm install open-last-project
apm install pretty-json
apm install project-manager
apm install script
apm install seti-ui
apm install seti-monokai
apm install symbols-tree-view
apm install terminal-status
apm install todo-show
apm install vim-mode
